demo/demo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'demo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', include('filepicker_demo.urls', namespace='demo')),
    url(r'^admin/', include(admin.site.urls)),
)

demo/filepicker_demo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from filepicker_demo.views import pick


urlpatterns = patterns('',
	url(r'^$', pick, name='pick'),
)

demo/filepicker_demo/models.py
from django.db import models
from django import forms
import django_filepicker


class BasicFilesModel(models.Model):
    text = models.CharField(max_length=64)

    def __unicode__(self):
        return 'Files chain {}. ID:{}'.format(self.text, self.pk)


class FileModel(models.Model):
    mid = models.ForeignKey(BasicFilesModel)
    fpfile = django_filepicker.models.FPFileField(
        upload_to='uploads', additional_params={'data-fp-multiple': 'true'})
    fpurl = models.URLField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return 'File from chain {}:id-{}. ID:{}'.format(
            self.mid.text, self.mid.pk, self.pk)

    def image_tag(self):
        return u'<img src="%s" />' % self.fpurl
    image_tag.short_description = 'Image'
    image_tag.allow_tags = True


class BasicFilesForm(forms.ModelForm):
    class Meta:
        model = BasicFilesModel
        fields = ['text']


class FileForm(forms.ModelForm):
    class Meta:
        model = FileModel
        fields = ['fpfile']

demo/filepicker_demo/views.py
from django.shortcuts import render

try:
    from .models import BasicFilesForm, FileForm
except ImportError:
    from models import BasicFilesForm, FileForm


def pick(request):
    message = None
    basic_form = BasicFilesForm()
    form = FileForm()

    if request.method == "POST":
        post = request.POST.dict()
        basic_form = BasicFilesForm(post)
        if basic_form.is_valid():
            f = basic_form.save()
            post['mid_id'] = f.id
        else:
            message = 'Invalid form'

        files_links = request.POST['fpfile'].split(',')
        if post.get('mid_id', None):
            for i, f in enumerate(request.FILES.getlist("fpfile")):
                form = FileForm(post)
                if form.is_valid():
                    fp = form.save(commit=False)
                    fp.fpfile = f
                    fp.fpurl = files_links[i]
                    fp.mid_id = post.get('mid_id')
                    fp.save()
                else:
                    message = "Invalid form"
            files = ", ".join([str(f) for f in request.FILES.getlist("fpfile")])
            message = "Save successful. URL for {0}: {1}".format(
                files, request.POST["fpfile"]) if not message else message

    return render(request, "home.html", {'form': form, 'message': message, 'basic_form': basic_form})

demo/filepicker_demo/templates/home.html
<html>
    <head>
        <title>Filepicker.io Django Library | Demo</title>
        {{ form.media }}
    </head>
    <body>
        <h1>Filepicker.io Django Library - Demo page</h1>
        {%if message%}<p>{{message}}</p>{%endif%}
        <form method="post" action="{% url 'demo:pick' %}">
            {%csrf_token%}
            {{ basic_form.as_p }}
            {{ form.as_p }}
            <p><input type="submit" value="Submit"/></p>
        </form>
        <h3>Form code:</h3>
        <pre>import django_filepicker

class TestModel(models.Model):
    text = models.CharField(max_length=64)
    fpfile = django_filepicker.models.FPFileField(upload_to='uploads')
</pre>
        <h3>Processing the form</h3>
        <pre>form = models.TestModelForm(request.POST, request.FILES)
if form.is_valid():
    #Save will read the data and upload it to the location defined in TestModel
    form.save()</pre>

        <hr/>
        <p>Code available on GitHub at <a href="https://github.com/Filepicker/django-filepicker">https://github.com/Filepicker/django-filepicker</a>.</p>
        <p>For more info and to get an api key, check out <a href="https://filepicker.io/">Filepicker.io</a>.</p>
    </body>
</html>

demo/templates/home.html
<html>
    <head>
        <title>Filepicker.io Django Library | Demo</title>
        {{ form.media }}
    </head>
    <body>
        <h1>Filepicker.io Django Library - Demo page</h1>
        {%if message%}<p>{{message}}</p>{%endif%}
        <form method="post" action="/">
            {%csrf_token%}
            {{ form.as_p }}
            <p><input type="submit" value="Submit"/></p>
        </form>
        <h3>Form code:</h3>
        <pre>import django_filepicker

class TestModel(models.Model):
    text = models.CharField(max_length=64)
    fpfile = django_filepicker.models.FPFileField(upload_to='uploads')
</pre>
        <h3>Processing the form</h3>
        <pre>form = models.TestModelForm(request.POST, request.FILES)
if form.is_valid():
    #Save will read the data and upload it to the location defined in TestModel
    form.save()</pre>

        <hr/>
        <p>Code available on GitHub at <a href="https://github.com/Filepicker/django-filepicker">https://github.com/Filepicker/django-filepicker</a>.</p>
        <p>For more info and to get an api key, check out <a href="https://filepicker.io/">Filepicker.io</a>.</p>
    </body>
</html>